corenlu:
  service:  http://10.60.1.101:5000/predict

golaxy_nlu:
  service:
    ner: http://10.20.18.126:48021/ners
    event: http://10.20.18.126:48022/events
    relation: http://10.20.18.126:48023/relations
  langs:
    zh: chinese
    en: english

gox_nlu:
  service:
    ner: http://10.20.8.36:9502/GOKS/v1.1/ner_general
    relation: http://10.20.8.36:9502/GOKS/v1.1/relation_extraction_general
